---
name: pre-commit

on:  # yamllint disable-line rule:truthy
  push:
    branches: ['develop', 'master']
  pull_request:
    branches: ['develop', 'master']

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3.1.1
      - uses: pre-commit/action@v2.0.3
